name: PR
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install dependencies
      run: yarn
    - name: Build the project
      run: yarn action-test
    - name: Setup finish
      run: echo "Setup complete"
