name: PR
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: tree
  print:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World - step-1"
    - run: echo "Hi Mom - step-2"
